//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsIntegration.OzoneService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OzoneService.OzoneSoap")]
    public interface OzoneSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasTokenExpired", ReplyAction="*")]
        ContactsIntegration.OzoneService.HasTokenExpiredResponse HasTokenExpired(ContactsIntegration.OzoneService.HasTokenExpiredRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        ContactsIntegration.OzoneService.AuthenticateResponse Authenticate(ContactsIntegration.OzoneService.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateWindows", ReplyAction="*")]
        ContactsIntegration.OzoneService.AuthenticateWindowsResponse AuthenticateWindows(ContactsIntegration.OzoneService.AuthenticateWindowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallFunction", ReplyAction="*")]
        ContactsIntegration.OzoneService.CallFunctionResponse CallFunction(ContactsIntegration.OzoneService.CallFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostData", ReplyAction="*")]
        ContactsIntegration.OzoneService.PostDataResponse PostData(ContactsIntegration.OzoneService.PostDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteData", ReplyAction="*")]
        ContactsIntegration.OzoneService.DeleteDataResponse DeleteData(ContactsIntegration.OzoneService.DeleteDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        ContactsIntegration.OzoneService.GetDataResponse GetData(ContactsIntegration.OzoneService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSelectData", ReplyAction="*")]
        ContactsIntegration.OzoneService.SearchSelectDataResponse SearchSelectData(ContactsIntegration.OzoneService.SearchSelectDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchData", ReplyAction="*")]
        ContactsIntegration.OzoneService.SearchDataResponse SearchData(ContactsIntegration.OzoneService.SearchDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuiWebXmlDocStm", ReplyAction="*")]
        ContactsIntegration.OzoneService.GuiWebXmlDocStmResponse GuiWebXmlDocStm(ContactsIntegration.OzoneService.GuiWebXmlDocStmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPoolCount", ReplyAction="*")]
        ContactsIntegration.OzoneService.GetPoolCountResponse GetPoolCount(ContactsIntegration.OzoneService.GetPoolCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasTokenExpiredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasTokenExpired", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.HasTokenExpiredRequestBody Body;
        
        public HasTokenExpiredRequest() {
        }
        
        public HasTokenExpiredRequest(ContactsIntegration.OzoneService.HasTokenExpiredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasTokenExpiredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        public HasTokenExpiredRequestBody() {
        }
        
        public HasTokenExpiredRequestBody(string TokenID) {
            this.TokenID = TokenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasTokenExpiredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasTokenExpiredResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.HasTokenExpiredResponseBody Body;
        
        public HasTokenExpiredResponse() {
        }
        
        public HasTokenExpiredResponse(ContactsIntegration.OzoneService.HasTokenExpiredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasTokenExpiredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool HasTokenExpiredResult;
        
        public HasTokenExpiredResponseBody() {
        }
        
        public HasTokenExpiredResponseBody(bool HasTokenExpiredResult) {
            this.HasTokenExpiredResult = HasTokenExpiredResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(ContactsIntegration.OzoneService.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string URL, string UserName, string Password) {
            this.URL = URL;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(ContactsIntegration.OzoneService.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(string AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateWindowsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWindows", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.AuthenticateWindowsRequestBody Body;
        
        public AuthenticateWindowsRequest() {
        }
        
        public AuthenticateWindowsRequest(ContactsIntegration.OzoneService.AuthenticateWindowsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateWindowsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        public AuthenticateWindowsRequestBody() {
        }
        
        public AuthenticateWindowsRequestBody(string URL) {
            this.URL = URL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateWindowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWindowsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.AuthenticateWindowsResponseBody Body;
        
        public AuthenticateWindowsResponse() {
        }
        
        public AuthenticateWindowsResponse(ContactsIntegration.OzoneService.AuthenticateWindowsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateWindowsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateWindowsResult;
        
        public AuthenticateWindowsResponseBody() {
        }
        
        public AuthenticateWindowsResponseBody(string AuthenticateWindowsResult) {
            this.AuthenticateWindowsResult = AuthenticateWindowsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFunction", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.CallFunctionRequestBody Body;
        
        public CallFunctionRequest() {
        }
        
        public CallFunctionRequest(ContactsIntegration.OzoneService.CallFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FunctionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Arguments;
        
        public CallFunctionRequestBody() {
        }
        
        public CallFunctionRequestBody(string TokenID, string FunctionID, string Arguments) {
            this.TokenID = TokenID;
            this.FunctionID = FunctionID;
            this.Arguments = Arguments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.CallFunctionResponseBody Body;
        
        public CallFunctionResponse() {
        }
        
        public CallFunctionResponse(ContactsIntegration.OzoneService.CallFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallFunctionResult;
        
        public CallFunctionResponseBody() {
        }
        
        public CallFunctionResponseBody(string CallFunctionResult) {
            this.CallFunctionResult = CallFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostData", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.PostDataRequestBody Body;
        
        public PostDataRequest() {
        }
        
        public PostDataRequest(ContactsIntegration.OzoneService.PostDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        public PostDataRequestBody() {
        }
        
        public PostDataRequestBody(string TokenID, string Data) {
            this.TokenID = TokenID;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.PostDataResponseBody Body;
        
        public PostDataResponse() {
        }
        
        public PostDataResponse(ContactsIntegration.OzoneService.PostDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostDataResult;
        
        public PostDataResponseBody() {
        }
        
        public PostDataResponseBody(string PostDataResult) {
            this.PostDataResult = PostDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteData", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.DeleteDataRequestBody Body;
        
        public DeleteDataRequest() {
        }
        
        public DeleteDataRequest(ContactsIntegration.OzoneService.DeleteDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        public DeleteDataRequestBody() {
        }
        
        public DeleteDataRequestBody(string TokenID, string Data) {
            this.TokenID = TokenID;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.DeleteDataResponseBody Body;
        
        public DeleteDataResponse() {
        }
        
        public DeleteDataResponse(ContactsIntegration.OzoneService.DeleteDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDataResult;
        
        public DeleteDataResponseBody() {
        }
        
        public DeleteDataResponseBody(string DeleteDataResult) {
            this.DeleteDataResult = DeleteDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(ContactsIntegration.OzoneService.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ItemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dict;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string TokenID, string BusObject, string ItemId, string Dict) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.ItemId = ItemId;
            this.Dict = Dict;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(ContactsIntegration.OzoneService.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSelectData", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.SearchSelectDataRequestBody Body;
        
        public SearchSelectDataRequest() {
        }
        
        public SearchSelectDataRequest(ContactsIntegration.OzoneService.SearchSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSelectDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Statement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Format;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IncludeRaw;
        
        public SearchSelectDataRequestBody() {
        }
        
        public SearchSelectDataRequestBody(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.Dict = Dict;
            this.Statement = Statement;
            this.Format = Format;
            this.IncludeRaw = IncludeRaw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSelectDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.SearchSelectDataResponseBody Body;
        
        public SearchSelectDataResponse() {
        }
        
        public SearchSelectDataResponse(ContactsIntegration.OzoneService.SearchSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchSelectDataResult;
        
        public SearchSelectDataResponseBody() {
        }
        
        public SearchSelectDataResponseBody(string SearchSelectDataResult) {
            this.SearchSelectDataResult = SearchSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchData", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.SearchDataRequestBody Body;
        
        public SearchDataRequest() {
        }
        
        public SearchDataRequest(ContactsIntegration.OzoneService.SearchDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Key;
        
        public SearchDataRequestBody() {
        }
        
        public SearchDataRequestBody(string TokenID, string BusObject, string RCode, string Dict, string Key) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.RCode = RCode;
            this.Dict = Dict;
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.SearchDataResponseBody Body;
        
        public SearchDataResponse() {
        }
        
        public SearchDataResponse(ContactsIntegration.OzoneService.SearchDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchDataResult;
        
        public SearchDataResponseBody() {
        }
        
        public SearchDataResponseBody(string SearchDataResult) {
            this.SearchDataResult = SearchDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuiWebXmlDocStmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuiWebXmlDocStm", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.GuiWebXmlDocStmRequestBody Body;
        
        public GuiWebXmlDocStmRequest() {
        }
        
        public GuiWebXmlDocStmRequest(ContactsIntegration.OzoneService.GuiWebXmlDocStmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuiWebXmlDocStmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Statement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Format;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IncludeRaw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ItemId;
        
        public GuiWebXmlDocStmRequestBody() {
        }
        
        public GuiWebXmlDocStmRequestBody(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw, string ItemId) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.Dict = Dict;
            this.Statement = Statement;
            this.Format = Format;
            this.IncludeRaw = IncludeRaw;
            this.ItemId = ItemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuiWebXmlDocStmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuiWebXmlDocStmResponse", Namespace="http://tempuri.org/", Order=0)]
        public ContactsIntegration.OzoneService.GuiWebXmlDocStmResponseBody Body;
        
        public GuiWebXmlDocStmResponse() {
        }
        
        public GuiWebXmlDocStmResponse(ContactsIntegration.OzoneService.GuiWebXmlDocStmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuiWebXmlDocStmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GuiWebXmlDocStmResult;
        
        public GuiWebXmlDocStmResponseBody() {
        }
        
        public GuiWebXmlDocStmResponseBody(System.Xml.Linq.XElement GuiWebXmlDocStmResult) {
            this.GuiWebXmlDocStmResult = GuiWebXmlDocStmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPoolCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPoolCountRequest {
        
        public GetPoolCountRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPoolCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPoolCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetPoolCountResult;
        
        public GetPoolCountResponse() {
        }
        
        public GetPoolCountResponse(int GetPoolCountResult) {
            this.GetPoolCountResult = GetPoolCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OzoneSoapChannel : ContactsIntegration.OzoneService.OzoneSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OzoneSoapClient : System.ServiceModel.ClientBase<ContactsIntegration.OzoneService.OzoneSoap>, ContactsIntegration.OzoneService.OzoneSoap {
        
        public OzoneSoapClient() {
        }
        
        public OzoneSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OzoneSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzoneSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzoneSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ContactsIntegration.OzoneService.HasTokenExpiredResponse HasTokenExpired(ContactsIntegration.OzoneService.HasTokenExpiredRequest request) {
            return base.Channel.HasTokenExpired(request);
        }
        
        public ContactsIntegration.OzoneService.AuthenticateResponse Authenticate(ContactsIntegration.OzoneService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public ContactsIntegration.OzoneService.AuthenticateWindowsResponse AuthenticateWindows(ContactsIntegration.OzoneService.AuthenticateWindowsRequest request) {
            return base.Channel.AuthenticateWindows(request);
        }
        
        public ContactsIntegration.OzoneService.CallFunctionResponse CallFunction(ContactsIntegration.OzoneService.CallFunctionRequest request) {
            return base.Channel.CallFunction(request);
        }
        
        public ContactsIntegration.OzoneService.PostDataResponse PostData(ContactsIntegration.OzoneService.PostDataRequest request) {
            return base.Channel.PostData(request);
        }
        
        public ContactsIntegration.OzoneService.DeleteDataResponse DeleteData(ContactsIntegration.OzoneService.DeleteDataRequest request) {
            return base.Channel.DeleteData(request);
        }
        
        public ContactsIntegration.OzoneService.GetDataResponse GetData(ContactsIntegration.OzoneService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public ContactsIntegration.OzoneService.SearchSelectDataResponse SearchSelectData(ContactsIntegration.OzoneService.SearchSelectDataRequest request) {
            return base.Channel.SearchSelectData(request);
        }
        
        public ContactsIntegration.OzoneService.SearchDataResponse SearchData(ContactsIntegration.OzoneService.SearchDataRequest request) {
            return base.Channel.SearchData(request);
        }
        
        public ContactsIntegration.OzoneService.GuiWebXmlDocStmResponse GuiWebXmlDocStm(ContactsIntegration.OzoneService.GuiWebXmlDocStmRequest request) {
            return base.Channel.GuiWebXmlDocStm(request);
        }
        
        public ContactsIntegration.OzoneService.GetPoolCountResponse GetPoolCount(ContactsIntegration.OzoneService.GetPoolCountRequest request) {
            return base.Channel.GetPoolCount(request);
        }
    }
}
