//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialsIntegration.ContactsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDetails", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactAddresses ContactAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactEmails ContactEmailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactNames ContactNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactOrganisationDetails ContactOrganisationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactPersonDetails ContactPersonDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactPhoneNumbers ContactPhoneNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactWebsites ContactWebsitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FINCustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoricIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReviewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactAddresses ContactAddresses {
            get {
                return this.ContactAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactAddressesField, value) != true)) {
                    this.ContactAddressesField = value;
                    this.RaisePropertyChanged("ContactAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactEmails ContactEmails {
            get {
                return this.ContactEmailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailsField, value) != true)) {
                    this.ContactEmailsField = value;
                    this.RaisePropertyChanged("ContactEmails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((this.ContactIDField.Equals(value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactNames ContactNames {
            get {
                return this.ContactNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNamesField, value) != true)) {
                    this.ContactNamesField = value;
                    this.RaisePropertyChanged("ContactNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactOrganisationDetails ContactOrganisationDetails {
            get {
                return this.ContactOrganisationDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactOrganisationDetailsField, value) != true)) {
                    this.ContactOrganisationDetailsField = value;
                    this.RaisePropertyChanged("ContactOrganisationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactPersonDetails ContactPersonDetails {
            get {
                return this.ContactPersonDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonDetailsField, value) != true)) {
                    this.ContactPersonDetailsField = value;
                    this.RaisePropertyChanged("ContactPersonDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactPhoneNumbers ContactPhoneNumbers {
            get {
                return this.ContactPhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneNumbersField, value) != true)) {
                    this.ContactPhoneNumbersField = value;
                    this.RaisePropertyChanged("ContactPhoneNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTypeField, value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactWebsites ContactWebsites {
            get {
                return this.ContactWebsitesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactWebsitesField, value) != true)) {
                    this.ContactWebsitesField = value;
                    this.RaisePropertyChanged("ContactWebsites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FINCustomerCode {
            get {
                return this.FINCustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FINCustomerCodeField, value) != true)) {
                    this.FINCustomerCodeField = value;
                    this.RaisePropertyChanged("FINCustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HistoricID {
            get {
                return this.HistoricIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoricIDField, value) != true)) {
                    this.HistoricIDField = value;
                    this.RaisePropertyChanged("HistoricID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDuplicate {
            get {
                return this.IsDuplicateField;
            }
            set {
                if ((this.IsDuplicateField.Equals(value) != true)) {
                    this.IsDuplicateField = value;
                    this.RaisePropertyChanged("IsDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((this.ReviewField.Equals(value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactOrganisationDetails", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactOrganisationDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> OrganisationCompanyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> OrganisationCompanyNumber {
            get {
                return this.OrganisationCompanyNumberField;
            }
            set {
                if ((this.OrganisationCompanyNumberField.Equals(value) != true)) {
                    this.OrganisationCompanyNumberField = value;
                    this.RaisePropertyChanged("OrganisationCompanyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganisationStatus {
            get {
                return this.OrganisationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationStatusField, value) != true)) {
                    this.OrganisationStatusField = value;
                    this.RaisePropertyChanged("OrganisationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganisationType {
            get {
                return this.OrganisationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationTypeField, value) != true)) {
                    this.OrganisationTypeField = value;
                    this.RaisePropertyChanged("OrganisationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPersonDetails", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactPersonDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfidentialReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PersonDateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PersonIsDeceasedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningCommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfidentialReason {
            get {
                return this.ConfidentialReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidentialReasonField, value) != true)) {
                    this.ConfidentialReasonField = value;
                    this.RaisePropertyChanged("ConfidentialReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PersonDateOfBirth {
            get {
                return this.PersonDateOfBirthField;
            }
            set {
                if ((this.PersonDateOfBirthField.Equals(value) != true)) {
                    this.PersonDateOfBirthField = value;
                    this.RaisePropertyChanged("PersonDateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonGender {
            get {
                return this.PersonGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonGenderField, value) != true)) {
                    this.PersonGenderField = value;
                    this.RaisePropertyChanged("PersonGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonIsDeceased {
            get {
                return this.PersonIsDeceasedField;
            }
            set {
                if ((this.PersonIsDeceasedField.Equals(value) != true)) {
                    this.PersonIsDeceasedField = value;
                    this.RaisePropertyChanged("PersonIsDeceased");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningComments {
            get {
                return this.WarningCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningCommentsField, value) != true)) {
                    this.WarningCommentsField = value;
                    this.RaisePropertyChanged("WarningComments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactAddresses", Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ItemName="ContactAddress")]
    [System.SerializableAttribute()]
    public class ContactAddresses : System.Collections.Generic.List<FinancialsIntegration.ContactsService.ContactAddress> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactEmails", Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ItemName="ContactEmail")]
    [System.SerializableAttribute()]
    public class ContactEmails : System.Collections.Generic.List<FinancialsIntegration.ContactsService.ContactEmail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactNames", Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ItemName="ContactName")]
    [System.SerializableAttribute()]
    public class ContactNames : System.Collections.Generic.List<FinancialsIntegration.ContactsService.ContactName> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactPhoneNumbers", Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ItemName="ContactPhoneNumber")]
    [System.SerializableAttribute()]
    public class ContactPhoneNumbers : System.Collections.Generic.List<FinancialsIntegration.ContactsService.ContactPhoneNumber> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactWebsites", Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ItemName="ContactWebsite")]
    [System.SerializableAttribute()]
    public class ContactWebsites : System.Collections.Generic.List<FinancialsIntegration.ContactsService.ContactWebsite> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactAddress", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactAddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactDeliveryAddress ContactDeliveryAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactOverseasAddress ContactOverseasAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactUrbanRuralAddress ContactUrbanRuralAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBillingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCareOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrologueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactAddressID {
            get {
                return this.ContactAddressIDField;
            }
            set {
                if ((this.ContactAddressIDField.Equals(value) != true)) {
                    this.ContactAddressIDField = value;
                    this.RaisePropertyChanged("ContactAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactAddressType {
            get {
                return this.ContactAddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactAddressTypeField, value) != true)) {
                    this.ContactAddressTypeField = value;
                    this.RaisePropertyChanged("ContactAddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactDeliveryAddress ContactDeliveryAddress {
            get {
                return this.ContactDeliveryAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDeliveryAddressField, value) != true)) {
                    this.ContactDeliveryAddressField = value;
                    this.RaisePropertyChanged("ContactDeliveryAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactOverseasAddress ContactOverseasAddress {
            get {
                return this.ContactOverseasAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactOverseasAddressField, value) != true)) {
                    this.ContactOverseasAddressField = value;
                    this.RaisePropertyChanged("ContactOverseasAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactUrbanRuralAddress ContactUrbanRuralAddress {
            get {
                return this.ContactUrbanRuralAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactUrbanRuralAddressField, value) != true)) {
                    this.ContactUrbanRuralAddressField = value;
                    this.RaisePropertyChanged("ContactUrbanRuralAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Invalid {
            get {
                return this.InvalidField;
            }
            set {
                if ((this.InvalidField.Equals(value) != true)) {
                    this.InvalidField = value;
                    this.RaisePropertyChanged("Invalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBilling {
            get {
                return this.IsBillingField;
            }
            set {
                if ((this.IsBillingField.Equals(value) != true)) {
                    this.IsBillingField = value;
                    this.RaisePropertyChanged("IsBilling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCareOf {
            get {
                return this.IsCareOfField;
            }
            set {
                if ((this.IsCareOfField.Equals(value) != true)) {
                    this.IsCareOfField = value;
                    this.RaisePropertyChanged("IsCareOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrent {
            get {
                return this.IsCurrentField;
            }
            set {
                if ((this.IsCurrentField.Equals(value) != true)) {
                    this.IsCurrentField = value;
                    this.RaisePropertyChanged("IsCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPostal {
            get {
                return this.IsPostalField;
            }
            set {
                if ((this.IsPostalField.Equals(value) != true)) {
                    this.IsPostalField = value;
                    this.RaisePropertyChanged("IsPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prologue {
            get {
                return this.PrologueField;
            }
            set {
                if ((object.ReferenceEquals(this.PrologueField, value) != true)) {
                    this.PrologueField = value;
                    this.RaisePropertyChanged("Prologue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDeliveryAddress", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactDeliveryAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoxLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryAddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryServiceIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownCityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoxLobby {
            get {
                return this.BoxLobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.BoxLobbyField, value) != true)) {
                    this.BoxLobbyField = value;
                    this.RaisePropertyChanged("BoxLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAddressType {
            get {
                return this.DeliveryAddressTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAddressTypeField, value) != true)) {
                    this.DeliveryAddressTypeField = value;
                    this.RaisePropertyChanged("DeliveryAddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryServiceIdentifier {
            get {
                return this.DeliveryServiceIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryServiceIdentifierField, value) != true)) {
                    this.DeliveryServiceIdentifierField = value;
                    this.RaisePropertyChanged("DeliveryServiceIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownCity {
            get {
                return this.TownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TownCityField, value) != true)) {
                    this.TownCityField = value;
                    this.RaisePropertyChanged("TownCity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactOverseasAddress", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactOverseasAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine4 {
            get {
                return this.AddressLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine4Field, value) != true)) {
                    this.AddressLine4Field = value;
                    this.RaisePropertyChanged("AddressLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine5 {
            get {
                return this.AddressLine5Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine5Field, value) != true)) {
                    this.AddressLine5Field = value;
                    this.RaisePropertyChanged("AddressLine5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactUrbanRuralAddress", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactUrbanRuralAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuralDeliveryIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAlphaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StreetNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorIdentifier {
            get {
                return this.FloorIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorIdentifierField, value) != true)) {
                    this.FloorIdentifierField = value;
                    this.RaisePropertyChanged("FloorIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorType {
            get {
                return this.FloorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorTypeField, value) != true)) {
                    this.FloorTypeField = value;
                    this.RaisePropertyChanged("FloorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuralDeliveryIdentifier {
            get {
                return this.RuralDeliveryIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.RuralDeliveryIdentifierField, value) != true)) {
                    this.RuralDeliveryIdentifierField = value;
                    this.RaisePropertyChanged("RuralDeliveryIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAlpha {
            get {
                return this.StreetAlphaField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAlphaField, value) != true)) {
                    this.StreetAlphaField = value;
                    this.RaisePropertyChanged("StreetAlpha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetDirection {
            get {
                return this.StreetDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetDirectionField, value) != true)) {
                    this.StreetDirectionField = value;
                    this.RaisePropertyChanged("StreetDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((this.StreetNumberField.Equals(value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetType {
            get {
                return this.StreetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetTypeField, value) != true)) {
                    this.StreetTypeField = value;
                    this.RaisePropertyChanged("StreetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownCity {
            get {
                return this.TownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TownCityField, value) != true)) {
                    this.TownCityField = value;
                    this.RaisePropertyChanged("TownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitIdentifier {
            get {
                return this.UnitIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitIdentifierField, value) != true)) {
                    this.UnitIdentifierField = value;
                    this.RaisePropertyChanged("UnitIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactEmail", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactEmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBillingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPreferredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactEmailID {
            get {
                return this.ContactEmailIDField;
            }
            set {
                if ((this.ContactEmailIDField.Equals(value) != true)) {
                    this.ContactEmailIDField = value;
                    this.RaisePropertyChanged("ContactEmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Invalid {
            get {
                return this.InvalidField;
            }
            set {
                if ((this.InvalidField.Equals(value) != true)) {
                    this.InvalidField = value;
                    this.RaisePropertyChanged("Invalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBilling {
            get {
                return this.IsBillingField;
            }
            set {
                if ((this.IsBillingField.Equals(value) != true)) {
                    this.IsBillingField = value;
                    this.RaisePropertyChanged("IsBilling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrent {
            get {
                return this.IsCurrentField;
            }
            set {
                if ((this.IsCurrentField.Equals(value) != true)) {
                    this.IsCurrentField = value;
                    this.RaisePropertyChanged("IsCurrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPreferred {
            get {
                return this.IsPreferredField;
            }
            set {
                if ((this.IsPreferredField.Equals(value) != true)) {
                    this.IsPreferredField = value;
                    this.RaisePropertyChanged("IsPreferred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactName", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactJFCName ContactJFCNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactNameIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactOrganisationName ContactOrganisationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactPersonName ContactPersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBillingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPreferredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactJFCName ContactJFCName {
            get {
                return this.ContactJFCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactJFCNameField, value) != true)) {
                    this.ContactJFCNameField = value;
                    this.RaisePropertyChanged("ContactJFCName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactNameID {
            get {
                return this.ContactNameIDField;
            }
            set {
                if ((this.ContactNameIDField.Equals(value) != true)) {
                    this.ContactNameIDField = value;
                    this.RaisePropertyChanged("ContactNameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactOrganisationName ContactOrganisationName {
            get {
                return this.ContactOrganisationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactOrganisationNameField, value) != true)) {
                    this.ContactOrganisationNameField = value;
                    this.RaisePropertyChanged("ContactOrganisationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactPersonName ContactPersonName {
            get {
                return this.ContactPersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonNameField, value) != true)) {
                    this.ContactPersonNameField = value;
                    this.RaisePropertyChanged("ContactPersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBilling {
            get {
                return this.IsBillingField;
            }
            set {
                if ((this.IsBillingField.Equals(value) != true)) {
                    this.IsBillingField = value;
                    this.RaisePropertyChanged("IsBilling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPreferred {
            get {
                return this.IsPreferredField;
            }
            set {
                if ((this.IsPreferredField.Equals(value) != true)) {
                    this.IsPreferredField = value;
                    this.RaisePropertyChanged("IsPreferred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameType {
            get {
                return this.NameTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NameTypeField, value) != true)) {
                    this.NameTypeField = value;
                    this.RaisePropertyChanged("NameType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactJFCName", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactJFCName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JFCNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JFCName {
            get {
                return this.JFCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JFCNameField, value) != true)) {
                    this.JFCNameField = value;
                    this.RaisePropertyChanged("JFCName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactOrganisationName", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactOrganisationName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationDivisionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganisationDivisionName {
            get {
                return this.OrganisationDivisionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationDivisionNameField, value) != true)) {
                    this.OrganisationDivisionNameField = value;
                    this.RaisePropertyChanged("OrganisationDivisionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganisationName {
            get {
                return this.OrganisationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationNameField, value) != true)) {
                    this.OrganisationNameField = value;
                    this.RaisePropertyChanged("OrganisationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPersonName", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactPersonName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonMiddleNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonFirstName {
            get {
                return this.PersonFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonFirstNameField, value) != true)) {
                    this.PersonFirstNameField = value;
                    this.RaisePropertyChanged("PersonFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonLastName {
            get {
                return this.PersonLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonLastNameField, value) != true)) {
                    this.PersonLastNameField = value;
                    this.RaisePropertyChanged("PersonLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonMiddleNames {
            get {
                return this.PersonMiddleNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonMiddleNamesField, value) != true)) {
                    this.PersonMiddleNamesField = value;
                    this.RaisePropertyChanged("PersonMiddleNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonTitle {
            get {
                return this.PersonTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonTitleField, value) != true)) {
                    this.PersonTitleField = value;
                    this.RaisePropertyChanged("PersonTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPhoneNumber", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactPhoneNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactPhoneNumberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPreferredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactPhoneNumberID {
            get {
                return this.ContactPhoneNumberIDField;
            }
            set {
                if ((this.ContactPhoneNumberIDField.Equals(value) != true)) {
                    this.ContactPhoneNumberIDField = value;
                    this.RaisePropertyChanged("ContactPhoneNumberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPreferred {
            get {
                return this.IsPreferredField;
            }
            set {
                if ((this.IsPreferredField.Equals(value) != true)) {
                    this.IsPreferredField = value;
                    this.RaisePropertyChanged("IsPreferred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactWebsite", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ContactWebsite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactWebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPreferredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactWebsiteID {
            get {
                return this.ContactWebsiteIDField;
            }
            set {
                if ((this.ContactWebsiteIDField.Equals(value) != true)) {
                    this.ContactWebsiteIDField = value;
                    this.RaisePropertyChanged("ContactWebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPreferred {
            get {
                return this.IsPreferredField;
            }
            set {
                if ((this.IsPreferredField.Equals(value) != true)) {
                    this.IsPreferredField = value;
                    this.RaisePropertyChanged("IsPreferred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IRISServiceFaultContract", Namespace="http://www.datacom.co.nz/IRIS/")]
    [System.SerializableAttribute()]
    public partial class IRISServiceFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaultCode {
            get {
                return this.FaultCodeField;
            }
            set {
                if ((this.FaultCodeField.Equals(value) != true)) {
                    this.FaultCodeField = value;
                    this.RaisePropertyChanged("FaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactsCollection", Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ItemName="ChangedContact")]
    [System.SerializableAttribute()]
    public class ContactsCollection : System.Collections.Generic.List<FinancialsIntegration.ContactsService.ChangedContact> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangedContact", Namespace="http://www.datacom.co.nz/IRIS/Contacts/")]
    [System.SerializableAttribute()]
    public partial class ChangedContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinancialsIntegration.ContactsService.ContactDetails ContactDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinancialsIntegration.ContactsService.ContactDetails ContactDetails {
            get {
                return this.ContactDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactDetailsField, value) != true)) {
                    this.ContactDetailsField = value;
                    this.RaisePropertyChanged("ContactDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNew {
            get {
                return this.IsNewField;
            }
            set {
                if ((this.IsNewField.Equals(value) != true)) {
                    this.IsNewField = value;
                    this.RaisePropertyChanged("IsNew");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.datacom.co.nz/IRIS/Contacts/", ConfigurationName="ContactsService.IContactsService")]
    public interface IContactsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacom.co.nz/IRIS/Contacts/IContactsService/GetContactDetails", ReplyAction="http://www.datacom.co.nz/IRIS/Contacts/IContactsService/GetContactDetailsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(FinancialsIntegration.ContactsService.IRISServiceFaultContract), Action="http://www.datacom.co.nz/IRIS/Contacts/IContactsService/GetContactDetailsIRISServ" +
            "iceFaultContractFault", Name="IRISServiceFaultContract", Namespace="http://www.datacom.co.nz/IRIS/")]
        FinancialsIntegration.ContactsService.ContactDetails GetContactDetails(long ContactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.datacom.co.nz/IRIS/Contacts/IContactsService/GetChangedContacts", ReplyAction="http://www.datacom.co.nz/IRIS/Contacts/IContactsService/GetChangedContactsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(FinancialsIntegration.ContactsService.IRISServiceFaultContract), Action="http://www.datacom.co.nz/IRIS/Contacts/IContactsService/GetChangedContactsIRISSer" +
            "viceFaultContractFault", Name="IRISServiceFaultContract", Namespace="http://www.datacom.co.nz/IRIS/")]
        FinancialsIntegration.ContactsService.ContactsCollection GetChangedContacts(System.DateTime SinceDateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactsServiceChannel : FinancialsIntegration.ContactsService.IContactsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactsServiceClient : System.ServiceModel.ClientBase<FinancialsIntegration.ContactsService.IContactsService>, FinancialsIntegration.ContactsService.IContactsService {
        
        public ContactsServiceClient() {
        }
        
        public ContactsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FinancialsIntegration.ContactsService.ContactDetails GetContactDetails(long ContactID) {
            return base.Channel.GetContactDetails(ContactID);
        }
        
        public FinancialsIntegration.ContactsService.ContactsCollection GetChangedContacts(System.DateTime SinceDateTime) {
            return base.Channel.GetChangedContacts(SinceDateTime);
        }
    }
}
