//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harness.OzoneServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OzoneServiceClient.OzoneSoap")]
    public interface OzoneSoap {
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasTokenExpired", ReplyAction="*")]
        Harness.OzoneServiceClient.HasTokenExpiredResponse HasTokenExpired(Harness.OzoneServiceClient.HasTokenExpiredRequest request);
        
        // CODEGEN: Generating message contract since element name URL from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        Harness.OzoneServiceClient.AuthenticateResponse Authenticate(Harness.OzoneServiceClient.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name URL from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateWindows", ReplyAction="*")]
        Harness.OzoneServiceClient.AuthenticateWindowsResponse AuthenticateWindows(Harness.OzoneServiceClient.AuthenticateWindowsRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallFunction", ReplyAction="*")]
        Harness.OzoneServiceClient.CallFunctionResponse CallFunction(Harness.OzoneServiceClient.CallFunctionRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostData", ReplyAction="*")]
        Harness.OzoneServiceClient.PostDataResponse PostData(Harness.OzoneServiceClient.PostDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteData", ReplyAction="*")]
        Harness.OzoneServiceClient.DeleteDataResponse DeleteData(Harness.OzoneServiceClient.DeleteDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        Harness.OzoneServiceClient.GetDataResponse GetData(Harness.OzoneServiceClient.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSelectData", ReplyAction="*")]
        Harness.OzoneServiceClient.SearchSelectDataResponse SearchSelectData(Harness.OzoneServiceClient.SearchSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchData", ReplyAction="*")]
        Harness.OzoneServiceClient.SearchDataResponse SearchData(Harness.OzoneServiceClient.SearchDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuiWebXmlDocStm", ReplyAction="*")]
        Harness.OzoneServiceClient.GuiWebXmlDocStmResponse GuiWebXmlDocStm(Harness.OzoneServiceClient.GuiWebXmlDocStmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPoolCount", ReplyAction="*")]
        int GetPoolCount();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasTokenExpiredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasTokenExpired", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.HasTokenExpiredRequestBody Body;
        
        public HasTokenExpiredRequest() {
        }
        
        public HasTokenExpiredRequest(Harness.OzoneServiceClient.HasTokenExpiredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasTokenExpiredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        public HasTokenExpiredRequestBody() {
        }
        
        public HasTokenExpiredRequestBody(string TokenID) {
            this.TokenID = TokenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasTokenExpiredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasTokenExpiredResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.HasTokenExpiredResponseBody Body;
        
        public HasTokenExpiredResponse() {
        }
        
        public HasTokenExpiredResponse(Harness.OzoneServiceClient.HasTokenExpiredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasTokenExpiredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool HasTokenExpiredResult;
        
        public HasTokenExpiredResponseBody() {
        }
        
        public HasTokenExpiredResponseBody(bool HasTokenExpiredResult) {
            this.HasTokenExpiredResult = HasTokenExpiredResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(Harness.OzoneServiceClient.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string URL, string UserName, string Password) {
            this.URL = URL;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(Harness.OzoneServiceClient.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(string AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateWindowsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWindows", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.AuthenticateWindowsRequestBody Body;
        
        public AuthenticateWindowsRequest() {
        }
        
        public AuthenticateWindowsRequest(Harness.OzoneServiceClient.AuthenticateWindowsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateWindowsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        public AuthenticateWindowsRequestBody() {
        }
        
        public AuthenticateWindowsRequestBody(string URL) {
            this.URL = URL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateWindowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWindowsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.AuthenticateWindowsResponseBody Body;
        
        public AuthenticateWindowsResponse() {
        }
        
        public AuthenticateWindowsResponse(Harness.OzoneServiceClient.AuthenticateWindowsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateWindowsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateWindowsResult;
        
        public AuthenticateWindowsResponseBody() {
        }
        
        public AuthenticateWindowsResponseBody(string AuthenticateWindowsResult) {
            this.AuthenticateWindowsResult = AuthenticateWindowsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFunction", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.CallFunctionRequestBody Body;
        
        public CallFunctionRequest() {
        }
        
        public CallFunctionRequest(Harness.OzoneServiceClient.CallFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FunctionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Arguments;
        
        public CallFunctionRequestBody() {
        }
        
        public CallFunctionRequestBody(string TokenID, string FunctionID, string Arguments) {
            this.TokenID = TokenID;
            this.FunctionID = FunctionID;
            this.Arguments = Arguments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.CallFunctionResponseBody Body;
        
        public CallFunctionResponse() {
        }
        
        public CallFunctionResponse(Harness.OzoneServiceClient.CallFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallFunctionResult;
        
        public CallFunctionResponseBody() {
        }
        
        public CallFunctionResponseBody(string CallFunctionResult) {
            this.CallFunctionResult = CallFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostData", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.PostDataRequestBody Body;
        
        public PostDataRequest() {
        }
        
        public PostDataRequest(Harness.OzoneServiceClient.PostDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        public PostDataRequestBody() {
        }
        
        public PostDataRequestBody(string TokenID, string Data) {
            this.TokenID = TokenID;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.PostDataResponseBody Body;
        
        public PostDataResponse() {
        }
        
        public PostDataResponse(Harness.OzoneServiceClient.PostDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostDataResult;
        
        public PostDataResponseBody() {
        }
        
        public PostDataResponseBody(string PostDataResult) {
            this.PostDataResult = PostDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteData", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.DeleteDataRequestBody Body;
        
        public DeleteDataRequest() {
        }
        
        public DeleteDataRequest(Harness.OzoneServiceClient.DeleteDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        public DeleteDataRequestBody() {
        }
        
        public DeleteDataRequestBody(string TokenID, string Data) {
            this.TokenID = TokenID;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.DeleteDataResponseBody Body;
        
        public DeleteDataResponse() {
        }
        
        public DeleteDataResponse(Harness.OzoneServiceClient.DeleteDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDataResult;
        
        public DeleteDataResponseBody() {
        }
        
        public DeleteDataResponseBody(string DeleteDataResult) {
            this.DeleteDataResult = DeleteDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(Harness.OzoneServiceClient.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ItemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dict;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string TokenID, string BusObject, string ItemId, string Dict) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.ItemId = ItemId;
            this.Dict = Dict;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(Harness.OzoneServiceClient.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSelectData", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.SearchSelectDataRequestBody Body;
        
        public SearchSelectDataRequest() {
        }
        
        public SearchSelectDataRequest(Harness.OzoneServiceClient.SearchSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSelectDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Statement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Format;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IncludeRaw;
        
        public SearchSelectDataRequestBody() {
        }
        
        public SearchSelectDataRequestBody(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.Dict = Dict;
            this.Statement = Statement;
            this.Format = Format;
            this.IncludeRaw = IncludeRaw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSelectDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.SearchSelectDataResponseBody Body;
        
        public SearchSelectDataResponse() {
        }
        
        public SearchSelectDataResponse(Harness.OzoneServiceClient.SearchSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchSelectDataResult;
        
        public SearchSelectDataResponseBody() {
        }
        
        public SearchSelectDataResponseBody(string SearchSelectDataResult) {
            this.SearchSelectDataResult = SearchSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchData", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.SearchDataRequestBody Body;
        
        public SearchDataRequest() {
        }
        
        public SearchDataRequest(Harness.OzoneServiceClient.SearchDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Key;
        
        public SearchDataRequestBody() {
        }
        
        public SearchDataRequestBody(string TokenID, string BusObject, string RCode, string Dict, string Key) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.RCode = RCode;
            this.Dict = Dict;
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.SearchDataResponseBody Body;
        
        public SearchDataResponse() {
        }
        
        public SearchDataResponse(Harness.OzoneServiceClient.SearchDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchDataResult;
        
        public SearchDataResponseBody() {
        }
        
        public SearchDataResponseBody(string SearchDataResult) {
            this.SearchDataResult = SearchDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuiWebXmlDocStmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuiWebXmlDocStm", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.GuiWebXmlDocStmRequestBody Body;
        
        public GuiWebXmlDocStmRequest() {
        }
        
        public GuiWebXmlDocStmRequest(Harness.OzoneServiceClient.GuiWebXmlDocStmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuiWebXmlDocStmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Statement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Format;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IncludeRaw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ItemId;
        
        public GuiWebXmlDocStmRequestBody() {
        }
        
        public GuiWebXmlDocStmRequestBody(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw, string ItemId) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.Dict = Dict;
            this.Statement = Statement;
            this.Format = Format;
            this.IncludeRaw = IncludeRaw;
            this.ItemId = ItemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuiWebXmlDocStmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuiWebXmlDocStmResponse", Namespace="http://tempuri.org/", Order=0)]
        public Harness.OzoneServiceClient.GuiWebXmlDocStmResponseBody Body;
        
        public GuiWebXmlDocStmResponse() {
        }
        
        public GuiWebXmlDocStmResponse(Harness.OzoneServiceClient.GuiWebXmlDocStmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuiWebXmlDocStmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GuiWebXmlDocStmResult;
        
        public GuiWebXmlDocStmResponseBody() {
        }
        
        public GuiWebXmlDocStmResponseBody(System.Xml.Linq.XElement GuiWebXmlDocStmResult) {
            this.GuiWebXmlDocStmResult = GuiWebXmlDocStmResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OzoneSoapChannel : Harness.OzoneServiceClient.OzoneSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OzoneSoapClient : System.ServiceModel.ClientBase<Harness.OzoneServiceClient.OzoneSoap>, Harness.OzoneServiceClient.OzoneSoap {
        
        public OzoneSoapClient() {
        }
        
        public OzoneSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OzoneSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzoneSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzoneSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.HasTokenExpiredResponse Harness.OzoneServiceClient.OzoneSoap.HasTokenExpired(Harness.OzoneServiceClient.HasTokenExpiredRequest request) {
            return base.Channel.HasTokenExpired(request);
        }
        
        public bool HasTokenExpired(string TokenID) {
            Harness.OzoneServiceClient.HasTokenExpiredRequest inValue = new Harness.OzoneServiceClient.HasTokenExpiredRequest();
            inValue.Body = new Harness.OzoneServiceClient.HasTokenExpiredRequestBody();
            inValue.Body.TokenID = TokenID;
            Harness.OzoneServiceClient.HasTokenExpiredResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).HasTokenExpired(inValue);
            return retVal.Body.HasTokenExpiredResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.AuthenticateResponse Harness.OzoneServiceClient.OzoneSoap.Authenticate(Harness.OzoneServiceClient.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public string Authenticate(string URL, string UserName, string Password) {
            Harness.OzoneServiceClient.AuthenticateRequest inValue = new Harness.OzoneServiceClient.AuthenticateRequest();
            inValue.Body = new Harness.OzoneServiceClient.AuthenticateRequestBody();
            inValue.Body.URL = URL;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            Harness.OzoneServiceClient.AuthenticateResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.AuthenticateWindowsResponse Harness.OzoneServiceClient.OzoneSoap.AuthenticateWindows(Harness.OzoneServiceClient.AuthenticateWindowsRequest request) {
            return base.Channel.AuthenticateWindows(request);
        }
        
        public string AuthenticateWindows(string URL) {
            Harness.OzoneServiceClient.AuthenticateWindowsRequest inValue = new Harness.OzoneServiceClient.AuthenticateWindowsRequest();
            inValue.Body = new Harness.OzoneServiceClient.AuthenticateWindowsRequestBody();
            inValue.Body.URL = URL;
            Harness.OzoneServiceClient.AuthenticateWindowsResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).AuthenticateWindows(inValue);
            return retVal.Body.AuthenticateWindowsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.CallFunctionResponse Harness.OzoneServiceClient.OzoneSoap.CallFunction(Harness.OzoneServiceClient.CallFunctionRequest request) {
            return base.Channel.CallFunction(request);
        }
        
        public string CallFunction(string TokenID, string FunctionID, string Arguments) {
            Harness.OzoneServiceClient.CallFunctionRequest inValue = new Harness.OzoneServiceClient.CallFunctionRequest();
            inValue.Body = new Harness.OzoneServiceClient.CallFunctionRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.FunctionID = FunctionID;
            inValue.Body.Arguments = Arguments;
            Harness.OzoneServiceClient.CallFunctionResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).CallFunction(inValue);
            return retVal.Body.CallFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.PostDataResponse Harness.OzoneServiceClient.OzoneSoap.PostData(Harness.OzoneServiceClient.PostDataRequest request) {
            return base.Channel.PostData(request);
        }
        
        public string PostData(string TokenID, string Data) {
            Harness.OzoneServiceClient.PostDataRequest inValue = new Harness.OzoneServiceClient.PostDataRequest();
            inValue.Body = new Harness.OzoneServiceClient.PostDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.Data = Data;
            Harness.OzoneServiceClient.PostDataResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).PostData(inValue);
            return retVal.Body.PostDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.DeleteDataResponse Harness.OzoneServiceClient.OzoneSoap.DeleteData(Harness.OzoneServiceClient.DeleteDataRequest request) {
            return base.Channel.DeleteData(request);
        }
        
        public string DeleteData(string TokenID, string Data) {
            Harness.OzoneServiceClient.DeleteDataRequest inValue = new Harness.OzoneServiceClient.DeleteDataRequest();
            inValue.Body = new Harness.OzoneServiceClient.DeleteDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.Data = Data;
            Harness.OzoneServiceClient.DeleteDataResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).DeleteData(inValue);
            return retVal.Body.DeleteDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.GetDataResponse Harness.OzoneServiceClient.OzoneSoap.GetData(Harness.OzoneServiceClient.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(string TokenID, string BusObject, string ItemId, string Dict) {
            Harness.OzoneServiceClient.GetDataRequest inValue = new Harness.OzoneServiceClient.GetDataRequest();
            inValue.Body = new Harness.OzoneServiceClient.GetDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.ItemId = ItemId;
            inValue.Body.Dict = Dict;
            Harness.OzoneServiceClient.GetDataResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.SearchSelectDataResponse Harness.OzoneServiceClient.OzoneSoap.SearchSelectData(Harness.OzoneServiceClient.SearchSelectDataRequest request) {
            return base.Channel.SearchSelectData(request);
        }
        
        public string SearchSelectData(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw) {
            Harness.OzoneServiceClient.SearchSelectDataRequest inValue = new Harness.OzoneServiceClient.SearchSelectDataRequest();
            inValue.Body = new Harness.OzoneServiceClient.SearchSelectDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.Dict = Dict;
            inValue.Body.Statement = Statement;
            inValue.Body.Format = Format;
            inValue.Body.IncludeRaw = IncludeRaw;
            Harness.OzoneServiceClient.SearchSelectDataResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).SearchSelectData(inValue);
            return retVal.Body.SearchSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.SearchDataResponse Harness.OzoneServiceClient.OzoneSoap.SearchData(Harness.OzoneServiceClient.SearchDataRequest request) {
            return base.Channel.SearchData(request);
        }
        
        public string SearchData(string TokenID, string BusObject, string RCode, string Dict, string Key) {
            Harness.OzoneServiceClient.SearchDataRequest inValue = new Harness.OzoneServiceClient.SearchDataRequest();
            inValue.Body = new Harness.OzoneServiceClient.SearchDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.RCode = RCode;
            inValue.Body.Dict = Dict;
            inValue.Body.Key = Key;
            Harness.OzoneServiceClient.SearchDataResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).SearchData(inValue);
            return retVal.Body.SearchDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Harness.OzoneServiceClient.GuiWebXmlDocStmResponse Harness.OzoneServiceClient.OzoneSoap.GuiWebXmlDocStm(Harness.OzoneServiceClient.GuiWebXmlDocStmRequest request) {
            return base.Channel.GuiWebXmlDocStm(request);
        }
        
        public System.Xml.Linq.XElement GuiWebXmlDocStm(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw, string ItemId) {
            Harness.OzoneServiceClient.GuiWebXmlDocStmRequest inValue = new Harness.OzoneServiceClient.GuiWebXmlDocStmRequest();
            inValue.Body = new Harness.OzoneServiceClient.GuiWebXmlDocStmRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.Dict = Dict;
            inValue.Body.Statement = Statement;
            inValue.Body.Format = Format;
            inValue.Body.IncludeRaw = IncludeRaw;
            inValue.Body.ItemId = ItemId;
            Harness.OzoneServiceClient.GuiWebXmlDocStmResponse retVal = ((Harness.OzoneServiceClient.OzoneSoap)(this)).GuiWebXmlDocStm(inValue);
            return retVal.Body.GuiWebXmlDocStmResult;
        }
        
        public int GetPoolCount() {
            return base.Channel.GetPoolCount();
        }
    }
}
