//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRC.OzoneContacts.OzoneService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OzoneService.OzoneSoap")]
    public interface OzoneSoap {
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasTokenExpired", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.HasTokenExpiredResponse HasTokenExpired(HRC.OzoneContacts.OzoneService.HasTokenExpiredRequest request);
        
        // CODEGEN: Generating message contract since element name URL from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.AuthenticateResponse Authenticate(HRC.OzoneContacts.OzoneService.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name URL from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateWindows", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.AuthenticateWindowsResponse AuthenticateWindows(HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CallFunction", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.CallFunctionResponse CallFunction(HRC.OzoneContacts.OzoneService.CallFunctionRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostData", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.PostDataResponse PostData(HRC.OzoneContacts.OzoneService.PostDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteData", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.DeleteDataResponse DeleteData(HRC.OzoneContacts.OzoneService.DeleteDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.GetDataResponse GetData(HRC.OzoneContacts.OzoneService.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchSelectData", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.SearchSelectDataResponse SearchSelectData(HRC.OzoneContacts.OzoneService.SearchSelectDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchData", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.SearchDataResponse SearchData(HRC.OzoneContacts.OzoneService.SearchDataRequest request);
        
        // CODEGEN: Generating message contract since element name TokenID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuiWebXmlDocStm", ReplyAction="*")]
        HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmResponse GuiWebXmlDocStm(HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPoolCount", ReplyAction="*")]
        int GetPoolCount();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasTokenExpiredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasTokenExpired", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.HasTokenExpiredRequestBody Body;
        
        public HasTokenExpiredRequest() {
        }
        
        public HasTokenExpiredRequest(HRC.OzoneContacts.OzoneService.HasTokenExpiredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasTokenExpiredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        public HasTokenExpiredRequestBody() {
        }
        
        public HasTokenExpiredRequestBody(string TokenID) {
            this.TokenID = TokenID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HasTokenExpiredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HasTokenExpiredResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.HasTokenExpiredResponseBody Body;
        
        public HasTokenExpiredResponse() {
        }
        
        public HasTokenExpiredResponse(HRC.OzoneContacts.OzoneService.HasTokenExpiredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HasTokenExpiredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool HasTokenExpiredResult;
        
        public HasTokenExpiredResponseBody() {
        }
        
        public HasTokenExpiredResponseBody(bool HasTokenExpiredResult) {
            this.HasTokenExpiredResult = HasTokenExpiredResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(HRC.OzoneContacts.OzoneService.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string URL, string UserName, string Password) {
            this.URL = URL;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(HRC.OzoneContacts.OzoneService.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(string AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateWindowsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWindows", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequestBody Body;
        
        public AuthenticateWindowsRequest() {
        }
        
        public AuthenticateWindowsRequest(HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateWindowsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string URL;
        
        public AuthenticateWindowsRequestBody() {
        }
        
        public AuthenticateWindowsRequestBody(string URL) {
            this.URL = URL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateWindowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateWindowsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.AuthenticateWindowsResponseBody Body;
        
        public AuthenticateWindowsResponse() {
        }
        
        public AuthenticateWindowsResponse(HRC.OzoneContacts.OzoneService.AuthenticateWindowsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateWindowsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateWindowsResult;
        
        public AuthenticateWindowsResponseBody() {
        }
        
        public AuthenticateWindowsResponseBody(string AuthenticateWindowsResult) {
            this.AuthenticateWindowsResult = AuthenticateWindowsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFunction", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.CallFunctionRequestBody Body;
        
        public CallFunctionRequest() {
        }
        
        public CallFunctionRequest(HRC.OzoneContacts.OzoneService.CallFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FunctionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Arguments;
        
        public CallFunctionRequestBody() {
        }
        
        public CallFunctionRequestBody(string TokenID, string FunctionID, string Arguments) {
            this.TokenID = TokenID;
            this.FunctionID = FunctionID;
            this.Arguments = Arguments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CallFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CallFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.CallFunctionResponseBody Body;
        
        public CallFunctionResponse() {
        }
        
        public CallFunctionResponse(HRC.OzoneContacts.OzoneService.CallFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CallFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CallFunctionResult;
        
        public CallFunctionResponseBody() {
        }
        
        public CallFunctionResponseBody(string CallFunctionResult) {
            this.CallFunctionResult = CallFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostData", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.PostDataRequestBody Body;
        
        public PostDataRequest() {
        }
        
        public PostDataRequest(HRC.OzoneContacts.OzoneService.PostDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        public PostDataRequestBody() {
        }
        
        public PostDataRequestBody(string TokenID, string Data) {
            this.TokenID = TokenID;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.PostDataResponseBody Body;
        
        public PostDataResponse() {
        }
        
        public PostDataResponse(HRC.OzoneContacts.OzoneService.PostDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostDataResult;
        
        public PostDataResponseBody() {
        }
        
        public PostDataResponseBody(string PostDataResult) {
            this.PostDataResult = PostDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteData", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.DeleteDataRequestBody Body;
        
        public DeleteDataRequest() {
        }
        
        public DeleteDataRequest(HRC.OzoneContacts.OzoneService.DeleteDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data;
        
        public DeleteDataRequestBody() {
        }
        
        public DeleteDataRequestBody(string TokenID, string Data) {
            this.TokenID = TokenID;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.DeleteDataResponseBody Body;
        
        public DeleteDataResponse() {
        }
        
        public DeleteDataResponse(HRC.OzoneContacts.OzoneService.DeleteDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDataResult;
        
        public DeleteDataResponseBody() {
        }
        
        public DeleteDataResponseBody(string DeleteDataResult) {
            this.DeleteDataResult = DeleteDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(HRC.OzoneContacts.OzoneService.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ItemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dict;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string TokenID, string BusObject, string ItemId, string Dict) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.ItemId = ItemId;
            this.Dict = Dict;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(HRC.OzoneContacts.OzoneService.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSelectDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSelectData", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.SearchSelectDataRequestBody Body;
        
        public SearchSelectDataRequest() {
        }
        
        public SearchSelectDataRequest(HRC.OzoneContacts.OzoneService.SearchSelectDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSelectDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Statement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Format;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IncludeRaw;
        
        public SearchSelectDataRequestBody() {
        }
        
        public SearchSelectDataRequestBody(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.Dict = Dict;
            this.Statement = Statement;
            this.Format = Format;
            this.IncludeRaw = IncludeRaw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchSelectDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchSelectDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.SearchSelectDataResponseBody Body;
        
        public SearchSelectDataResponse() {
        }
        
        public SearchSelectDataResponse(HRC.OzoneContacts.OzoneService.SearchSelectDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchSelectDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchSelectDataResult;
        
        public SearchSelectDataResponseBody() {
        }
        
        public SearchSelectDataResponseBody(string SearchSelectDataResult) {
            this.SearchSelectDataResult = SearchSelectDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchData", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.SearchDataRequestBody Body;
        
        public SearchDataRequest() {
        }
        
        public SearchDataRequest(HRC.OzoneContacts.OzoneService.SearchDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Key;
        
        public SearchDataRequestBody() {
        }
        
        public SearchDataRequestBody(string TokenID, string BusObject, string RCode, string Dict, string Key) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.RCode = RCode;
            this.Dict = Dict;
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.SearchDataResponseBody Body;
        
        public SearchDataResponse() {
        }
        
        public SearchDataResponse(HRC.OzoneContacts.OzoneService.SearchDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchDataResult;
        
        public SearchDataResponseBody() {
        }
        
        public SearchDataResponseBody(string SearchDataResult) {
            this.SearchDataResult = SearchDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuiWebXmlDocStmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuiWebXmlDocStm", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequestBody Body;
        
        public GuiWebXmlDocStmRequest() {
        }
        
        public GuiWebXmlDocStmRequest(HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuiWebXmlDocStmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TokenID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dict;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Statement;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Format;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IncludeRaw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ItemId;
        
        public GuiWebXmlDocStmRequestBody() {
        }
        
        public GuiWebXmlDocStmRequestBody(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw, string ItemId) {
            this.TokenID = TokenID;
            this.BusObject = BusObject;
            this.Dict = Dict;
            this.Statement = Statement;
            this.Format = Format;
            this.IncludeRaw = IncludeRaw;
            this.ItemId = ItemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuiWebXmlDocStmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuiWebXmlDocStmResponse", Namespace="http://tempuri.org/", Order=0)]
        public HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmResponseBody Body;
        
        public GuiWebXmlDocStmResponse() {
        }
        
        public GuiWebXmlDocStmResponse(HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuiWebXmlDocStmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GuiWebXmlDocStmResult;
        
        public GuiWebXmlDocStmResponseBody() {
        }
        
        public GuiWebXmlDocStmResponseBody(System.Xml.Linq.XElement GuiWebXmlDocStmResult) {
            this.GuiWebXmlDocStmResult = GuiWebXmlDocStmResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OzoneSoapChannel : HRC.OzoneContacts.OzoneService.OzoneSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OzoneSoapClient : System.ServiceModel.ClientBase<HRC.OzoneContacts.OzoneService.OzoneSoap>, HRC.OzoneContacts.OzoneService.OzoneSoap {
        
        public OzoneSoapClient() {
        }
        
        public OzoneSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OzoneSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzoneSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzoneSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.HasTokenExpiredResponse HRC.OzoneContacts.OzoneService.OzoneSoap.HasTokenExpired(HRC.OzoneContacts.OzoneService.HasTokenExpiredRequest request) {
            return base.Channel.HasTokenExpired(request);
        }
        
        public bool HasTokenExpired(string TokenID) {
            HRC.OzoneContacts.OzoneService.HasTokenExpiredRequest inValue = new HRC.OzoneContacts.OzoneService.HasTokenExpiredRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.HasTokenExpiredRequestBody();
            inValue.Body.TokenID = TokenID;
            HRC.OzoneContacts.OzoneService.HasTokenExpiredResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).HasTokenExpired(inValue);
            return retVal.Body.HasTokenExpiredResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.AuthenticateResponse HRC.OzoneContacts.OzoneService.OzoneSoap.Authenticate(HRC.OzoneContacts.OzoneService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public string Authenticate(string URL, string UserName, string Password) {
            HRC.OzoneContacts.OzoneService.AuthenticateRequest inValue = new HRC.OzoneContacts.OzoneService.AuthenticateRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.AuthenticateRequestBody();
            inValue.Body.URL = URL;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            HRC.OzoneContacts.OzoneService.AuthenticateResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.AuthenticateWindowsResponse HRC.OzoneContacts.OzoneService.OzoneSoap.AuthenticateWindows(HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequest request) {
            return base.Channel.AuthenticateWindows(request);
        }
        
        public string AuthenticateWindows(string URL) {
            HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequest inValue = new HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.AuthenticateWindowsRequestBody();
            inValue.Body.URL = URL;
            HRC.OzoneContacts.OzoneService.AuthenticateWindowsResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).AuthenticateWindows(inValue);
            return retVal.Body.AuthenticateWindowsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.CallFunctionResponse HRC.OzoneContacts.OzoneService.OzoneSoap.CallFunction(HRC.OzoneContacts.OzoneService.CallFunctionRequest request) {
            return base.Channel.CallFunction(request);
        }
        
        public string CallFunction(string TokenID, string FunctionID, string Arguments) {
            HRC.OzoneContacts.OzoneService.CallFunctionRequest inValue = new HRC.OzoneContacts.OzoneService.CallFunctionRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.CallFunctionRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.FunctionID = FunctionID;
            inValue.Body.Arguments = Arguments;
            HRC.OzoneContacts.OzoneService.CallFunctionResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).CallFunction(inValue);
            return retVal.Body.CallFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.PostDataResponse HRC.OzoneContacts.OzoneService.OzoneSoap.PostData(HRC.OzoneContacts.OzoneService.PostDataRequest request) {
            return base.Channel.PostData(request);
        }
        
        public string PostData(string TokenID, string Data) {
            HRC.OzoneContacts.OzoneService.PostDataRequest inValue = new HRC.OzoneContacts.OzoneService.PostDataRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.PostDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.Data = Data;
            HRC.OzoneContacts.OzoneService.PostDataResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).PostData(inValue);
            return retVal.Body.PostDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.DeleteDataResponse HRC.OzoneContacts.OzoneService.OzoneSoap.DeleteData(HRC.OzoneContacts.OzoneService.DeleteDataRequest request) {
            return base.Channel.DeleteData(request);
        }
        
        public string DeleteData(string TokenID, string Data) {
            HRC.OzoneContacts.OzoneService.DeleteDataRequest inValue = new HRC.OzoneContacts.OzoneService.DeleteDataRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.DeleteDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.Data = Data;
            HRC.OzoneContacts.OzoneService.DeleteDataResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).DeleteData(inValue);
            return retVal.Body.DeleteDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.GetDataResponse HRC.OzoneContacts.OzoneService.OzoneSoap.GetData(HRC.OzoneContacts.OzoneService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(string TokenID, string BusObject, string ItemId, string Dict) {
            HRC.OzoneContacts.OzoneService.GetDataRequest inValue = new HRC.OzoneContacts.OzoneService.GetDataRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.GetDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.ItemId = ItemId;
            inValue.Body.Dict = Dict;
            HRC.OzoneContacts.OzoneService.GetDataResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.SearchSelectDataResponse HRC.OzoneContacts.OzoneService.OzoneSoap.SearchSelectData(HRC.OzoneContacts.OzoneService.SearchSelectDataRequest request) {
            return base.Channel.SearchSelectData(request);
        }
        
        public string SearchSelectData(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw) {
            HRC.OzoneContacts.OzoneService.SearchSelectDataRequest inValue = new HRC.OzoneContacts.OzoneService.SearchSelectDataRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.SearchSelectDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.Dict = Dict;
            inValue.Body.Statement = Statement;
            inValue.Body.Format = Format;
            inValue.Body.IncludeRaw = IncludeRaw;
            HRC.OzoneContacts.OzoneService.SearchSelectDataResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).SearchSelectData(inValue);
            return retVal.Body.SearchSelectDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.SearchDataResponse HRC.OzoneContacts.OzoneService.OzoneSoap.SearchData(HRC.OzoneContacts.OzoneService.SearchDataRequest request) {
            return base.Channel.SearchData(request);
        }
        
        public string SearchData(string TokenID, string BusObject, string RCode, string Dict, string Key) {
            HRC.OzoneContacts.OzoneService.SearchDataRequest inValue = new HRC.OzoneContacts.OzoneService.SearchDataRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.SearchDataRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.RCode = RCode;
            inValue.Body.Dict = Dict;
            inValue.Body.Key = Key;
            HRC.OzoneContacts.OzoneService.SearchDataResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).SearchData(inValue);
            return retVal.Body.SearchDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmResponse HRC.OzoneContacts.OzoneService.OzoneSoap.GuiWebXmlDocStm(HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequest request) {
            return base.Channel.GuiWebXmlDocStm(request);
        }
        
        public System.Xml.Linq.XElement GuiWebXmlDocStm(string TokenID, string BusObject, string Dict, string Statement, string Format, bool IncludeRaw, string ItemId) {
            HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequest inValue = new HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequest();
            inValue.Body = new HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmRequestBody();
            inValue.Body.TokenID = TokenID;
            inValue.Body.BusObject = BusObject;
            inValue.Body.Dict = Dict;
            inValue.Body.Statement = Statement;
            inValue.Body.Format = Format;
            inValue.Body.IncludeRaw = IncludeRaw;
            inValue.Body.ItemId = ItemId;
            HRC.OzoneContacts.OzoneService.GuiWebXmlDocStmResponse retVal = ((HRC.OzoneContacts.OzoneService.OzoneSoap)(this)).GuiWebXmlDocStm(inValue);
            return retVal.Body.GuiWebXmlDocStmResult;
        }
        
        public int GetPoolCount() {
            return base.Channel.GetPoolCount();
        }
    }
}
